# Generated by Django 6.0.5 on 2026-05-14 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='food',
            fields=[
                ('orderid', models.IntegerField(primary_key=True, serialize=False)),
                ('Itemname', models.CharField(max_length=20)),
                ('OrderQty', models.IntegerField()),
                ('TotalAmount', models.FloatField()),
                ('Delivery_Address', models.CharField(max_length=100)),
            ],
        ),
    ]
